[package]
name = "graphyne"
version = "0.1.0"
edition = "2024"
description = "A simple rust client for sending messages to Graphite"

[dependencies]
bon = "3.8.1"

[dev-dependencies]
insta = { version = "1.43.2", features = ["filters"] }
